print("Welcome to the Band Name Generator.")
var1 = input("What's the name of the city you grew up in?\n")
var2= input("What's your pet's name?\n")
print("your bane name coud be",var1,var2)
print("your bane name coud be",var1," ", var2)
